server:
  port: 8088
# DataSource Config
spring:
  application:
    name: frank-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/frank-api
    username: root
    password: 12345678
  session:
    timeout: 86400
  servlet:
    multipart:
      max-file-size: 5MB  # 单个文件最大限制
      max-request-size: 10MB # 单次请求最大限制
# mybatis-plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
# aliyun OSS 配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-web-frank
    region: cn-beijing
# 上传头像的配置
avatar:
  upload:
    max-width: 800 # 最大宽度
    max-height: 800 # 最大高度
    quality: 0.7 # 压缩质量（0-1）
    allowed-types: jpg,jpeg,png # 允许的文件类型
# frank-api-gateway 配置
frank:
  api:
    gateway:
      baseUrl: http://localhost:8123
# nacos : d9cbCuZmnFsI 7vPLGAh8DVlL sh startup.sh -m standalone
# dubbo配置
dubbo:
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=7vPLGAh8DVlL
    # This will enable application-level service discovery only (the recommended service discovery method for Dubbo3).
    # For users upgrading from Dubbo2.x, please set the value to 'all' for smooth migration.
    register-mode: instance
  protocol:
    name: tri
    port: 50051
  application:
    qos-enable: true
    name: ${spring.application.name}
    qos-port: 22222
    qos-accept-foreign-ip: false
    logger: slf4j

